server:
  error:
    include-message: always
    include-binding-errors: always

# bruno username: postgres password: 1234
# luaksz username: postgres password: 1qaz#EDC

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: 1qaz#EDC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/  # Ścieżka do folderu zawierającego szablony Thymeleaf
    suffix: .html  # Rozszerzenie plików szablonów Thymeleaf
    cache: false  # Ustawienie cache na false, aby zapewnić dynamiczną aktualizację szablonów podczas rozwoju
    mode: HTML5  # Tryb HTML5 dla Thymeleaf
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
